PRAGMA encoding = 'UTF-16';
CREATE VIRTUAL TABLE vt0 USING fts4(c0);
CREATE TABLE t1(a TEXT UNIQUE);
INSERT INTO vt0 VALUES ('3078');
INSERT INTO vt0(c0) VALUES('integrity-check'), ('xp'), (NULL);
INSERT INTO t1 VALUES ('3078'), ('xp'), (000), (NULL);
CREATE INDEX i1 ON t1(a) WHERE a IS NOT NULL;
SELECT * FROM vt0 WHERE c0 ISNULL;
SELECT * FROM vt0 JOIN t1 WHERE t1.a = vt0.c0;